# autogenerated Android.mk
ifeq ($(TARGET_ARCH),x86)
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libmfx_mix_h264ve.so
LOCAL_BUILT_MODULE_STEM:=libmfx_mix_h264ve.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE := libmfx_mix_h264ve
LOCAL_MODULE_STEM:=libmfx_mix_h264ve.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libva libva-android libva-tpi libintelmetadatabuffer libmfxhw32 libstlport liblog libdl libutils libc libstdc++ libm
include $(BUILD_PREBUILT)
endif
