# autogenerated Android.mk
ifeq ($(TARGET_ARCH),x86)
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libwidirtsp.so
LOCAL_BUILT_MODULE_STEM:=libwidirtsp.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libwidirtsp
LOCAL_MODULE_STEM:=libwidirtsp.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=liblog libutils libcutils libnetutils libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libwidirtspsink.so
LOCAL_BUILT_MODULE_STEM:=libwidirtspsink.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libwidirtspsink
LOCAL_MODULE_STEM:=libwidirtspsink.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=liblog libutils libcutils libbinder libnetutils libwidirtsp libc libstdc++ libm
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_IS_HOST_MODULE:=
LOCAL_MODULE_CLASS:=SHARED_LIBRARIES
LOCAL_MODULE_TAGS:=optional
OVERRIDE_BUILT_MODULE_PATH:=$(PRODUCT_OUT)/obj/lib
LOCAL_UNINSTALLABLE_MODULE:=
LOCAL_SRC_FILES:=target/libwidirtspsink_jni.so
LOCAL_BUILT_MODULE_STEM:=libwidirtspsink_jni.so
LOCAL_STRIP_MODULE:=
LOCAL_MODULE:=libwidirtspsink_jni
LOCAL_MODULE_STEM:=libwidirtspsink_jni.so
LOCAL_CERTIFICATE:=
LOCAL_MODULE_PATH:=$(PRODUCT_OUT)/system/lib
LOCAL_REQUIRED_MODULES:=
LOCAL_SHARED_LIBRARIES:=libcutils libbinder libutils libandroid_runtime libnativehelper libwidirtspsink libc libstdc++ libm
include $(BUILD_PREBUILT)
endif
